### PR TITLE
Adds support for JSON Number instead of float

### PR DESCRIPTION
**Pull request by crystalin**

### CODE REVIEW

**Comment by dgrijalva** [comment]
Probably a useful idea.  Have you investigated why tests are failing?

**Comment by pxue** [comment]
any progress on this one? currently marshalling/unmarshalling int64 claims values will return float64 by default. [json.UseNumber](https://golang.org/pkg/encoding/json/#Decoder.UseNumber) should be used and numerical values in Claims should be returned as `json.Number` type imho.

**Comment by dgrijalva** [comment]
I haven't really dug into it.  The provided patch fails the unit tests.  If someone wants to take a crack at fixing that, I don't see a reason not to include this.

**Comment by dgrijalva** [comment]
This PR doesn't pass tests.  Superseded by #96 and #98.

**Pull request closed without merging**
