### PR TITLE
Add RSASSA-PSS signatures

### PR DESCRIPTION
**Pull request by patbaker82**
Support for:

- PS256
- PS384
- PS512

Testing including

### CODE REVIEW

**Comment by patbaker82** [comment]
Note, test doesn't pass on go 1.3.3 due to API differences in crypto/rsa

**Comment by dgrijalva** [comment]
Can we use build flags to omit these two files when compiling for 1.3?  I'd be happy with requiring 1.4 for this feature, but I'd rather not drop 1.3 support if possible.

**Comment by dgrijalva** [comment]
http://golang.org/pkg/go/build/

**Comment by patbaker82** [comment]
Shouldn't be a problem.  I'll need to separate out the tests into their own file (currently bundled with straight rsa).  The tests were so similar I was looking to avoid a rework.  Perhaps I will duplicate for now and refine any duplicated functions at a later point.

**Comment by patbaker82** [comment]
@dgrijalva I updated the pull request:

- Verify and Sign will no longer accept []byte
- Build only for >= 1.4

**Comment by dgrijalva** [comment]
great!

**Pull request merged**
