### PR TITLE
Update token.go

### PR DESCRIPTION
**Pull request by TimurStash**
Fixed a bug with header token parsing

### CODE REVIEW

**Comment by dgrijalva** [comment]
This does not pass the tests. I think there's a legit bug here, but that's not it.  The format for the header in question is `bearer :token:`.  The additional character being absorbed is the space.

**Comment by TimurStash** [comment]
Sorry, I didn't work with tests, first of all I am not so skilled, and also I really have no time. But the bug I fixed is obvious: ah[0:6] here we cut first 6 characters which should be "BEARER", then we have to take the key which starts from 7th position, so we have to slice this way ah[6:], but not ah[7:] - actually ah[7:] starts from 8th character so we loose the first char of the key.

**Comment by dgrijalva** [comment]
The key does not start in the 7th position. There is a whitespace character.

**Comment by dgrijalva** [comment]
See the following for the specification: http://self-issued.info/docs/draft-ietf-oauth-v2-bearer.html#authz-header

**Comment by dgrijalva** [comment]
This PR fails tests and hasn't seen activity.  I'm going to close.  Feel free to re-open if you want to pick it up again.

**Pull request closed without merging**
