### PR TITLE
Release 3.0.0

### PR DESCRIPTION
**Pull request by dgrijalva**
See #75 

* [x] Drop support for `[]byte` when using RSA signing methods
* [x] Support for custom Claim types
* [x] Migrate `ParseFromRequest` to a subpackage.  
* [x] Modify request parsing API to provide more flexibility.
* [x] Updated release notes and documentation
* [x] Decide on landing #139 (leeway and validation options)

### CODE REVIEW

**Comment by itsjamie** [comment]
Hey @dgrijalva, I'd be interested in putting the time in to get this ready to be merged if you can let me know what needs to happen.

**Comment by danilobuerger** [comment]
@dgrijalva do you still intend to work on this?

**Comment by dgrijalva** [comment]
Yep. The main remaining thing is getting the oauth/http stuff out into a subpackage and cleaning it up.  I just haven't had time.

**Comment by dgrijalva** [comment]
This is just about ready to land.  As soon as #137 has been looked at, we can complete the README updates and ship it.  Any remaining issues to be resolved?

**Comment by StephanDollberg** [comment]
Has the issue I mentioned here now been fixed? https://github.com/dgrijalva/jwt-go/pull/73

Thanks!

**Comment by dgrijalva** [comment]
@StephanDollberg That thread is super long, but I believe we have addressed all the issues.  There are several example uses you can review to see usage.

**Comment by StephanDollberg** [comment]
Oh yeah sorry. It was the issue with `https://github.com/dgrijalva/jwt-go/blob/release_3_0_0/token.go#L33` having to return a pointer to `MapClaims`.

**Comment by dgrijalva** [comment]
That has been solved, though it's not super elegant. I ended up special casing it. I think it's ok, but we can watch it.

-dave

**Comment by Noah-Huppert** [comment]
Anything I can do to help push 3.0 out?

**Comment by dgrijalva** [comment]
There are no remaining issues for 3.0.0.  Shall we ship it (finally)?

**Comment by dgrijalva** [comment]
The only thing that got left out is support for leeway.  The documentation says about it:

> Implementers MAY provide for some small leeway, usually no more than a few minutes, to account for clock skew

I think we can add support for this by modifying `Claims`. See #131.  Does anyone want to make the case for this in 3.0?

**Comment by dgrijalva** [comment]
Actually, the change proposed in #131 would enable things like iss validation, etc in the future.  Let me see how hard it would be...

**Comment by dgrijalva** [comment]
See #139

**Comment by dgrijalva** [comment]
Let's wait on #139.  Seems like there are several viable approaches.  If you need leeway support today, see #131 for an easy workaround.

**Pull request merged**
