### PR TITLE
Make error message case consistent

### PR DESCRIPTION
**Pull request by jesse-c**
I noticed that almost all error messages began with a capital letter—and I realise this is a _very trivial_ change (so, feel free to close)—so I thought I'd spend the minute to make the changes. 😅

### CODE REVIEW

**Comment by lutzhorn** [comment]
https://github.com/golang/go/wiki/Errors says:

> Error strings should not start with a capital letter because they'll often be prefixed before printing:

So this PR should not be merged.

**Comment by jesse-c** [comment]
Good point! So the consistency change should be the other way around. I'll do an update.

**Comment by jesse-c** [comment]
Done. :) Let me know if I've missed anything—I grep'd for `errorf`, `errors.new`, and just straight `error` and went through the results. I left all the testing `Errorf` calls.

**Comment by lutzhorn** [comment]
LGTM

**Comment by dgrijalva** [comment]
Landed in release branch for 4.0.0.

Thank you

**Pull request closed without merging**
