### PR TITLE
Add ECDSA signatures

### PR DESCRIPTION
**Pull request by patbaker82**
Support for:

ES256
ES384
ES512

Testing including, however only for the Verify and Parse functions.  Also didn't include benchmarks due to my time requirements.  If you absolutely must have these, I'll see when I can get to them.

### CODE REVIEW

**Comment by dgrijalva** [comment]
This looks good.  I wonder about the merits of accepting `[]byte` and having built in PEM decoding.  It's a great convenience, but I kind of regret including it with rsa.  It makes it way easier to provide the wrong type of key to the wrong decoder.

**Comment by dgrijalva** [comment]
My vote would be to keep the decoding helpers, but drop support for passing `[]byte` to `Verify` and `Sign`.  Long term, I'll probably do the same with RSA.

**Comment by patbaker82** [comment]
@dgrijalva I like that idea.  Ok I will update.

**Comment by patbaker82** [comment]
@dgrijalva Pull request has been updated based on your comments.

**Pull request merged**
